name: SIPs-run-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastp 
  - fastqc 
  - bwa 
  - hisat2 
  - star
  - salmon
  - stringtie
  - cufflinks  
  - htseq 
  - subread  
